services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Port d'exposition interne pour l'application
    volumes:
      - .:/app        # Monte le dossier actuel dans le conteneur
      - /app/node_modules # Évite les conflits avec node_modules de l'hôte
    environment:
      NODE_ENV: development
    networks:
      - db-network

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"  # Expose le port 80 pour l'accès public
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Utilise un fichier de configuration personnalisé pour nginx
  #   networks:
  #     - app-network
  #   depends_on:
  #     - app

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: drowssap
      POSTGRES_DB: projet
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: drowssap
    ports:
      - "5050:80"
    networks:
      - db-network
    depends_on:
      - db

volumes:
  db-data:

networks:
  db-network:
