services:
  app:
    build:
      context: .
      dockerfile: ./prod/Dockerfile
    ports:
      - "3000:3000"  # Port d'exposition interne pour l'application
    environment:
      NODE_ENV: production
      POSTGRES_DB: projet
      POSTGRES_USER: user
      POSTGRES_PASSWORD: drowssap
      AUTH_SECRET: ${AUTH_SECRET} 
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: drowssap
      POSTGRES_DB: projet
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
